---
output: 
  html_document:
    toc: true
title: "UK Biobank GWAS analysis with simulated data"
author: "Dr. Umesh Ghoshdastider, ETH Zurich"
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

# Generate data
```{r}
# no of samples
n=10000
# random number seed for reproducibility
set.seed(1)
# SNP
snp=c(rep('AA',n*.9),rep('AB', n*.095),rep('BB', n*.005))
#snp=sample(c('AA','AB','BB'), n, replace=T)

# Sex
sex=sample(c(0,1), n, replace=T)

# phenotype: obesity
obesity=sample(c(0,1), n,replace=T)

# phenotype: bmi
# biobank mean 27.4, sd 4.8 
# http://biobank.ndph.ox.ac.uk/showcase/field.cgi?id=21001
bmi=rnorm(n,mean=27.4,sd=4.8)
#hist(bmi)

# age
age=rnorm(n,mean=57.3,sd=8.3)

# PCs of population
set.seed(1)
pc1=rnorm(n, mean=0, sd=10)
set.seed(2)
pc2=rnorm(n, mean=0, sd=10)
set.seed(3)
pc3=rnorm(n, mean=0, sd=10)
set.seed(4)
pc4=rnorm(n, mean=0, sd=10)
set.seed(5)
pc5=rnorm(n, mean=0, sd=10)

df=data.frame(obesity,bmi,snp,age,sex,pc1,pc2,pc3,pc4,pc5)
summary(df)
```
```{r}
boxplot(df)
```

# Linear Model, continuous outcome
```{r}
bmi_lm = lm( bmi ~ snp + age + sex + pc1 + pc2 + pc3 + pc4 + pc5, df)
#bmi_lm = lm( bmi ~ snp + age + sex, df)
summary(bmi_lm)
```
# Logistic Regression, binary outcome
```{r}
obesity_glm = glm( obesity ~ snp + age + sex + pc1 + pc2 + pc3 + pc4 + pc5, family= binomial, data=df)
summary(obesity_glm)
```
# Chisq and Fisher's Exact Test
```{r}
t = table(factor(df$snp), factor(df$obesity))
t
chisq.test(t)
fisher.test(t[1:2,])
```

